apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-3
spec:
  selector:
    matchLabels:
      app: test3
  replicas: 1
  template:
    metadata:
      labels:
        app: test3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - test
      containers:
      - name: nginx
        image: nginx:1.14
      tolerations:
      - key: app
        operator: Equal
        value: test1
        effect: NoExecute
