apiVersion: apps/v1
kind: Deployment
metadata:
  #Unique key for the deployment instance
  name: web-app-deployment-11
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        #the deployment labels selector to this value
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
