apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-14
  labels:
    app: app-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-14
  template:
    metadata:
      labels:
        app: app-14
    spec:
      containers:
      - image: nginx:1.14
        name: app-14
        env:
        - name: DB_Host
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Host
        - name: DB_user
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_user
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password
