apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod-19
  labels:
    name: multicontainer-pod-19
spec:
  containers:
  - name: nginx
    image: nginx:1.14
  - name: readiness
    image: busybox
    args:
      - /bin/sh
      - -c
      - sleep 500
