apiVersion: apps/v1
kind: Deployment
metadata:
  #Unique key for the deployment instance
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        #the deployment labels selector to this value
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14