apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-16
  labels:
    app: app-16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-16
  template:
    metadata:
      labels:
        app: app-16
    spec:
      containers:
      - image: nginx:1.14
        name: app-16
        envFrom:
          - configMapRef:
              name: app-config
