apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2021-09-27T03:14:49Z"
  labels:
    app: test
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: multinode-demo-m02
    kubernetes.io/os: linux
  name: multinode-demo-m02
  resourceVersion: "1253"
  uid: 5172be67-e778-4ee1-b621-310feb8665cb
spec:
  podCIDR: 10.244.1.0/24
  podCIDRs:
  - 10.244.1.0/24
status:
  addresses:
  - address: 192.168.49.3
    type: InternalIP
  - address: multinode-demo-m02
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: 25152772Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 3995080Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 25152772Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 3995080Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2021-09-27T03:26:02Z"
    lastTransitionTime: "2021-09-27T03:14:49Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2021-09-27T03:26:02Z"
    lastTransitionTime: "2021-09-27T03:14:49Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2021-09-27T03:26:02Z"
    lastTransitionTime: "2021-09-27T03:14:49Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2021-09-27T03:26:02Z"
    lastTransitionTime: "2021-09-27T03:15:46Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - k8s.gcr.io/etcd@sha256:4ad90a11b55313b182afc186b9876c8e891531b8db4c9bf1541953021618d0e2
    - k8s.gcr.io/etcd:3.4.13-0
    sizeBytes: 253392289
  - names:
    - kubernetesui/dashboard@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6
    - kubernetesui/dashboard:v2.1.0
    sizeBytes: 225733746
  - names:
    - k8s.gcr.io/kube-proxy@sha256:3ee783402715225d6bc483b3a2f8ea11adcb997d00fb5ca2f74734023ade0561
    - k8s.gcr.io/kube-proxy:v1.21.2
    sizeBytes: 130869239
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:c86c3855e360b1483008c30c8deaed2b1a92f63eaacec819a90a0ffe04df152b
    - k8s.gcr.io/kube-apiserver:v1.21.2
    sizeBytes: 125624711
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:2ea5e2885485fc20aaa15a0033d50e47ce7c559bf292741c16604984088bd700
    - k8s.gcr.io/kube-controller-manager:v1.21.2
    sizeBytes: 119829772
  - names:
    - kindest/kindnetd@sha256:838bc1706e38391aefaa31fd52619fe8e57ad3dfb0d0ff414d902367fcc24c3c
    - kindest/kindnetd:v20210326-1e038dc5
    sizeBytes: 118029627
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:d372f36741c015e30d36aef958a021de4af7218c467edac91796fb03aab478b4
    - k8s.gcr.io/kube-scheduler:v1.21.2
    sizeBytes: 50640140
  - names:
    - k8s.gcr.io/coredns/coredns@sha256:cc8fb77bc2a0541949d1d9320a641b82fd392b0d3d8145469ca4709ae769980e
    - k8s.gcr.io/coredns/coredns:v1.8.0
    sizeBytes: 42454755
  - names:
    - kubernetesui/metrics-scraper@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf
    - kubernetesui/metrics-scraper:v1.0.4
    sizeBytes: 36937728
  - names:
    - gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944
    - gcr.io/k8s-minikube/storage-provisioner:v5
    sizeBytes: 31465472
  - names:
    - k8s.gcr.io/pause@sha256:6c3835cab3980f11b83277305d0d736051c32b17606f5ec59f1dda67c9ba3810
    - k8s.gcr.io/pause:3.4.1
    sizeBytes: 682696
  nodeInfo:
    architecture: amd64
    bootID: 456e5b50-20d3-4230-af22-48e34a61233c
    containerRuntimeVersion: docker://20.10.7
    kernelVersion: 5.11.0-34-generic
    kubeProxyVersion: v1.21.2
    kubeletVersion: v1.21.2
    machineID: 760e67beb8554645829f2357c8eb4ae7
    operatingSystem: linux
    osImage: Ubuntu 20.04.2 LTS
    systemUUID: e70beaa7-0473-4d08-854d-d70628895362
