apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  #This define which ports are going to be represented by this service
  #This service becomes a network endpoint for other services or external users
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
